#!/usr/bin/env bash
set -e -o pipefail
# shellcheck disable=SC2034
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

## Cleanup
APP_DIR="$(dirname "${SCRIPT_DIR}")"
cd "${APP_DIR}"

# Python artefacts
find . -name '__pycache__' -print0 | xargs -r0 rm -rf 2>/dev/null
find . -name '.pybuild' -print0 | xargs -r0 rm -rf 2>/dev/null
