#!/usr/bin/env bash
set -e -o pipefail
# shellcheck disable=SC2034
SCRIPT="${0##*/}"
SCRIPT_DIR="$(dirname "$(realpath -e "${0}")")"

## Run
APP_DIR="$(dirname "${SCRIPT_DIR}")"

# PIP compile

# (production)
[ -e "${APP_DIR}/requirements.txt" ] && rm -i "${APP_DIR}/requirements.txt"
pip-compile --output-file="${APP_DIR}/requirements.txt" "${APP_DIR}/requirements.in"

# (development)
[ -e "${APP_DIR}/dev/requirements.txt" ] && rm -i "${APP_DIR}/dev/requirements.txt"
pip-compile --output-file="${APP_DIR}/devel/requirements.txt" "${APP_DIR}/devel/requirements.in" "${APP_DIR}/requirements.in"
